apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: hprod
spec:
  serviceName: "gitea"
  replicas: 2
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: gitea/gitea:1.25
          # ports:
          #   - containerPort: 3000
          #   - containerPort: 22
          volumeMounts:
            - name: gitea-volume
              mountPath: /data
          envFrom:
            - configMapRef:
                name: gitea-config
            - secretRef:
                name: gitea-secret
      volumes:
        - name: gitea-volume
          persistentVolumeClaim:
            claimName: gitea-pvc
      affinity:
        # prefer the Raspberries fully server dedicated (with ubuntu-server)
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 5
              preference:
                matchExpressions:
                  - key: server-dedicated
                    operator: In
                    values: ["true"]
        # prefer to be provisoned alongwise it's postgress pod
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values: ["gitea-postgres"]
                topologyKey: "cluster-name"
        # strongly prefer to have it's pod provisoned in diferent nodes
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values: ["gitea"]
                topologyKey: "cluster-name"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-postgres
  namespace: hprod
spec:
  serviceName: "gitea-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: gitea-postgres
  template:
    metadata:
      labels:
        app: gitea-postgres
    spec:
      containers:
        - name: gitea-postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: gitea-postgres-volume
              mountPath: /var/lib/postgresql/data
          envFrom:
            - secretRef:
                name: gitea-postgres-secret
      volumes:
        - name: gitea-postgres-volume
          persistentVolumeClaim:
            claimName: gitea-postgres-pvc
      affinity:
        # prefer the Raspberries fully server dedicated (with ubuntu-server)
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 5
              preference:
                matchExpressions:
                  - key: server-dedicated
                    operator: In
                    values: ["true"]
        # prefer to be provisoned alongwise it's gitea pod
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values: ["gitea"]
                topologyKey: "cluster-name"
        # strongly prefer to have it's pod provisoned in diferent nodes
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values: ["gitea-postgres"]
                topologyKey: "cluster-name"
