apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gitea-postgres.yml
  - gitea.yml
  - ingress.yml

secretGenerator:
  - name: gitea-postgres-secret
    type: Opaque
    literals:
      - POSTGRES_USER=gitea
      - POSTGRES_DB=gitea
      # MUDE ESTA SENHA ANTES DE APLICAR!
      - POSTGRES_PASSWORD="CHANGE_ME_PLEASE"
