apiVersion: v1
kind: StorageClass
metadata:
  name: gitea-hprod-expandable
provisioner: rancher.io/local-path
allowVolumeExpansion: false
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
