apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hprod

resources:
  - ../../base

patches:
  - path: patch-configmap.yml
  - path: patch-gitea.yml
  - path: patch-gitea-postgres.yml
  - path: patch-service.yml
  - path: patch-pvc.yml
  - path: patch-secret.yml
