apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gitea-hprod-expandable
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gitea-hprod-expandable
  resources:
    requests:
      storage: 16Gi
