#!/usr/bin/env bash
# hl-net-sec => homelab-network-security

show_help() {
  echo "
Home Lab Cluster CLI (hlccli)
Usage:
  ./hl-net-sec <command> [args...]

Commands:
  install [pi]

  Flags:
  -pi01
  -pi02
  -pi03
  -pi04

  Behavior:
    - Install all the needed network security on the server, then configure the needed ports that needes to be open at the given pi
"
}

install_network_security_tools() {
  echo "updating system and installing ufw..."

  sudo apt update
  sudo apt install ufw -y
}

protect() {
  # deny all entrance, allow output
  sudo ufw default deny incoming
  sudo ufw default allow outgoing
}

allow_pi01() {
  echo "allowing in pi01..."

  echo "ssh service..."
  sudo ufw allow 22/tcp
}

allow_pi02() {
  echo "allowing in pi02..."

  echo "docker-proxy -> vaultwarden"
  sudo ufw allow 8090/tcp

  echo "ssh service..."
  sudo ufw allow 22/tcp
}

allow_pi03() {
  echo "allowing in pi03..."

  echo "docker-proxy -> gitea ssh"
  sudo ufw allow 222/tcp

  echo "docker-proxy -> gitea"
  sudo ufw allow 3000/tcp

  echo "docker-proxy -> seafile"
  sudo ufw allow 8063/tcp

  echo "ssh service..."
  sudo ufw allow 22/tcp
}

allow_pi04() {
  echo "allowing in pi04..."

  echo "docker-proxy -> restaurant-manager"
  sudo ufw allow 8273/tcp

  echo "docker-proxy -> bentopdf"
  sudo ufw allow 3030/tcp

  echo "docker-proxy -> stirling-pdf"
  sudo ufw allow 8095/tcp

  echo "docker-proxy -> ldavincif-portal"
  sudo ufw allow 8080/tcp

  echo "ssh service..."
  sudo ufw allow 22/tcp

}

activate() {
  sudo ufw enable
  sudo ufw status verbose
}

confirmation() {
  sudo systemctl status cloudflared
}

setup_pi_homelab() {
  if [[ $# -lt 1 ]]; then
    echo "[ERROR] Missing pi flag, where is the net-set being installed? (01..04)." >&2
    show_help
    exit 1
  fi

  install_network_security_tools
  protect

  local pi="$1"; shift
  case "$pi" in
    --pi01|--pi1|-pi01|-pi1)
      allow_pi01 "$@"
      ;;
    --pi02|--pi2|-pi02|-pi2)
      allow_pi02 "$@"
      ;;
    --pi03|--pi3|-pi03|-pi3)
      allow_pi03 "$@"
      ;;
    --pi04|--pi4|-pi04|-pi4)
      allow_pi04 "$@"
      ;;
    *)
      echo "[ERROR] Unknown flag: $1" >&2
      show_help
      exit 1
      ;;
  esac

  activate
}

check_status() {
  # general status
  sudo fail2ban-client status

  # SSH specific status
  sudo fail2ban-client status sshd

  # check logs do fail2ban
  # sudo tail -f /var/log/fail2ban.log
}

# fail2ban() {
#   # IN DEV! DONT USE!
#   echo "fail2ban FUNCTION IN DEV, DON'T USE IT!"
#   return
#   sudo apt-get install fail2ban -y
#   sudo systemctl enable fail2ban.service
#   # set up File: /etc/fail2ban/jail.local
#   # sudo systemctl restart fail2ban.service
# }

main() {
  if [[ $# -lt 1 ]]; then
    show_help
    exit 1
  fi

  local cmd="$1"; shift

  case "$cmd" in
    i|install)
      setup_pi_homelab "$@"
      ;;
    status)
      check_status "$@"
      ;;
    -h|--help|help)
      show_help
      ;;
    *)
      echo "[ERROR] Unknown command: $cmd" >&2
      show_help
      exit 1
      ;;
  esac
}

main "$@"
