apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hdev

resources:
  - ../../base
  # - storageclass.yml

patches:
  - path: patch-configmap.yml
  - path: patch-gitea.yml
  - path: patch-pvc.yml
  - path: patch-storageclass.yml
  - path: patch-gitea-postgres.yml
  - path: patch-service.yml
  - path: patch-secret.yml
