apiVersion: v1
kind: Kustomization

namespace: hdev

resources:
  - ../../base
  # - storageclass.yml

patches:
  - path: patch-gitea.yml
  - path: patch-pvc.yml
  - path: patch-storageclass.yml
  - path: patch-gitea-postgres.yml
