apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hdev

resources:
  - ../../base
  # - storageclass.yml

patches:
  - path: patch-configmap.yml
  - path: patch-gitea.yml
  - path: patch-pvc.yml
  - path: patch-storageclass.yml
  - path: patch-gitea-postgres.yml
  - path: patch-service.yml
  - path: patch-secret.yml

# patchesJson6902:
#   - target:
#       kind: StorageClass
#       name: gitea-hprod-expandable
#     patch: |-
#       - op: replace
#         path: /metadata/name
#         value: gitea-hdev-nonexpand
#       - op: replace
#         path: /spec/allowVolumeExpansion
#         value: false
#       - op: replace
#         path: /spec/reclaimPolicy
#         value: Delete
