apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: hdev
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: gitea
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 150m
              memory: 256Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-postgres
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: gitea-postgres
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 150m
              memory: 256Mi
