apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc
  namespace: hdev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gitea-hdev-nonexpand
  resources:
    requests:
      storage: 500Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-postgres-pvc
  namespace: hdev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gitea-hdev-nonexpand
  resources:
    requests:
      storage: 1Gi
