apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gitea-storage
  resources:
    requests:
      storage: 500Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gitea-storage
  resources:
    requests:
      storage: 1Gi
